[package]
name = "chip8-emulator"
version = "0.0.1"
authors = ["Aleksander Wons <aleksander.wons@gmail.com>"]

[dependencies]
rand = "^0.5"
pancurses = "^0.16"
mio = "^0.6"
termios = "^0.3"
libc = "^0.2"